### ISSUE TITLE
'messages' and 'res' error

### ISSUE THREAD

**Issue by nikolai-tech** [ediziks/BingGPT-Discord-Bot#23]

**Comment by nikolai-tech** [comment]
closed

**Comment by Bonhovis** [comment]
@ediziks I checked @nikolai-tech's original raised issue (before it was edited) and they have the same exact errors I'm seeing.

Is this simply because I'm using `/ask`? I did see that it was listed as a [known issue ](https://github.com/ediziks/BingGPT-Discord-Bot#known-issues) but was unsure if it's completely broken or not?

Any help would be amazing. Thanks in advance.
