### ISSUE TITLE
auth problem

### ISSUE THREAD

**Issue by Noob-A** [ediziks/BingGPT-Discord-Bot#6]
<img width="650" alt="image" src="https://user-images.githubusercontent.com/59875489/230782862-81e6354e-2f89-4ca7-8414-1120eb538fbc.png">
<img width="650" alt="image" src="https://user-images.githubusercontent.com/59875489/230782877-b24c1e25-f403-429d-a972-fac382eb46c5.png">
why doesnt it work?

**Comment by ediziks** [comment]
Never had the same issue before but assuming it might be related to an incorrect cookie string (head to the README to check 1 more time). Or, the account is not accepted to the beta which sounds less likely for your case. It would be great if you could let me know @Noob-A how you fixed the problem and what the issue was!

**Comment by ediziks** [comment]
I assume the issue is figured out by now. Feel free to raise it again in case of a need.

**Comment by 6Xian9** [comment]
I am experiencing the same issue
